version: '3'

services:
  server:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    image: flowenv:1.0
    volumes:
      - '$PWD:/app'
    ports:
      - '8000:8000'
    tty: true
