version: '3'

services:
  server:
    build:
    context: ./
    dockerfile: ./docker/Dockerfile
    image: myubuntu:flowenv
    volumes:
      - '$PWD:/app'
    ports:
      - '8000:8000'
    tty: true
