FROM node:4-onbuild

RUN ln -s --force /usr/bin/nodejs /usr/local/bin/node \
    && ln -s --force /usr/bin/npm /usr/local/bin/npm

WORKDIR /app

COPY . /app/

RUN rm -rf /app/node_modules/.babel-cli.DELETE

# RUN mv -n /app/node_modules/babel-cli \
  #    /app/node_modules/.babel-cli.DELETE

RUN npm install \
    && npm rebuild node-sass

CMD npm run start